name: Build and push image to ECR

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      chart_folder:
        required: false
        type: string
        default: chart
      tag_suffix:
        required: false
        type: string
      project_working_dir:
        required: false
        type: string
        default: "./"
      img_working_dir:
        required: false
        type: string
        default: "/opt/ambiente"
      run_tests:
        required: false
        type: boolean
        default: true
      test_name:
        required: false
        type: string
        default: "test_docker"
    secrets:
      db_password:
        required: false
      aws_role:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      issues: read
      pull-requests: write
      id-token: write

    env:
      REPO_NAME: ${{ inputs.repo_name }}
      CHART_FOLDER: ${{ inputs.chart_folder }}
      TAG_SUFFIX: ${{ inputs.tag_suffix }}
      IMG_WORKING_DIR: ${{ inputs.img_working_dir }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Helm Chart
        id: chart
        uses: jacobtomlinson/gha-read-helm-chart@master
        with:
          path: ${{ inputs.project_working_dir }}${{ env.CHART_FOLDER }}

      - name: Build image
        id: build
        env:
          IMAGE_NAME: ${{ env.REPO_NAME }}:${{ steps.chart.outputs.appVersion }}.${{ github.run_number }}${{ env.TAG_SUFFIX }}
        run: |
          cd ${{ inputs.project_working_dir }}
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Run tests
        if: ${{ inputs.run_tests }}
        id: tests
        run: |
          docker build -t ${{ env.REPO_NAME }}db docker-db/.
          docker volume create tests
          docker network create ${{ env.REPO_NAME }}net
          docker run -d --network ${{ env.REPO_NAME }}net --name ${{ env.REPO_NAME }}db ${{ env.REPO_NAME }}db:latest

          mkdir ${{ github.workspace }}/test-results
          docker run --mount type=bind,source=${{ github.workspace }}/test-results,target=${{ env.IMG_WORKING_DIR }}/${{ env.REPO_NAME }}/tests-results/  \
            --network ${{ env.REPO_NAME }}net --name ${{ env.REPO_NAME }} \
            --env 'DB_HOST=${{ env.REPO_NAME }}db' \
            --env 'DB_USER=postgres' \
            --env 'DB_PASSWORD=${{ secrets.DB_PASSWORD }}' \
            --entrypoint fab ${{ env.REPO_NAME }}:${{ steps.chart.outputs.appVersion }}.${{ github.run_number }}${{ env.TAG_SUFFIX }} ${{ inputs.test_name }}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: ${{ inputs.run_tests }}
        with:
          report_individual_runs: "true"
          files: "**/test-results/*.xml"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHubAction
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.REPO_NAME }}
          IMAGE_TAG: ${{ steps.chart.outputs.appVersion }}.${{ github.run_number }}${{ env.TAG_SUFFIX }}
        run: |
          docker tag $REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
